processes:
  "Manganese from Market": ~
  "Chromium from Market": ~
  "Nickel from Market": ~
  "Molibdenium from Market": ~
  "Copper from Market": ~
  "Silicon from market": ~
  "Vanadium from market": ~
  "Titanium from market": ~
  "Niobium from market": ~
  "Aluminium from market": ~
  "Zinc from Market": ~
  "Limestone from Market": ~
  "Process Gas": ~
  "Fuel Oil from Market": 1.0
  "Diesel from Market": 0.0
  "Ethanol from Market": 0.5
  "Biodiesel from Market": 0.5
  "Natural gas from Market": 1.0
  "LPG from Market": 0.0
  "Biomethane from Market": 0.0
  "Hydrogen (Electrolysis) from Market": 0.0
  "Hydrogen (Methane reforming) from Market": 0.0
  "Wood from Market": 0
  "Charcoal from Market": 0
  "Coal from Market": 1.0
  "Anthracite Coal from Market": 1.0
  "PCI Coal from Market": 1.0
  "Coke Petroleum from Market": 0.0
  "Coke Mineral from Market": 0.0
  "Electricity from Market": 1
  "Electricity Hydro from Market": 0.0
  "Electricity Eolic from Market": 0.0
  "Electricity Solar from Market": 0.0
  "Electricity Biomass from Market": 0.0
  "Electricity Production": 1
  "Charcoal Production (Wood)": 1.0
  "Charcoal Production": 1.0
  "Coke Production": 1.0
  "Steam Production": 1.0
  "Utility Plant": 1.0
  "Nitrogen from Market": 0.0
  "Nitrogen Production": 1.0
  "Oxygen from Market": 1.0
  "Oxygen Production": 1.0
  "Burnt Lime from Market": 0.0
  "Burnt Lime Production": 1.0
  "Dolomite from Market": 0.0
  "Dolomite Production": 1.0
  "Alloys Mix for Low Alloy Steel (LAS)": 0.0
  "Alloys Mix for High Alloy Steel (HAS)": 0.0
  "Scrap Purchase": 1
  "Iron Ore from Market": 1
  "Direct Iron ore": 0.0
  "Sintering": 1
  "Pelletizing": 1
  "Blast Furnace": 1.0
  "Direct Reduction Iron": 1.0
  "Iron Foundry": 0.0
  "Electric Arc Furnace": 1.0
  "Basic Oxygen Furnace": 1.0

  "Regular Steel": 1
  "Steel Refining (Low Alloy)": 1
  "Steel Refining (High Alloy)": 1

  "Continuous Casting (R)": 1
  "Continuous Casting (L)": 1
  "Continuous Casting (H)": 0

  "Hot Rolling": 0
  "Rod/bar/section Mill": 0
  "Ingot Casting": 0

  "Cold Rolling": 0

  "Steel Thermal Treatment": 0
  "Hot Dip Metal Coating": 0
  "Electrolytic Metal Coating": 0

  "Steel Thermal Treatment (CR)": 0
  "Hot Dip Met(eal Coating (CR)": 0
  "Electrolytic Metal Coating (CR)": 0

  "Bypass Raw→IP3": 0
  "Bypass CR→IP3": 0

  "Direct use of Basic Steel Products (IP4)": 0
  "Casting/Extrusion/Conformation": 0
  "Stamping/calendering/lamination": 0
  "Machining": 0

  "No Coating": 0
  "Hot Dip Metal Coating FP": 0
  "Electrolytic Metal Coating FP": 0
  "Organic or Sintetic Coating (painting)": 0