#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import sys

import yaml


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from forge.steel_core_api_v2 import RouteConfig, ScenarioInputs, run_scenario


DEFAULT_ROUTES = ["BF-BOF", "DRI-EAF", "EAF-Scrap"]

# Route → default scenario YAML (mirrors app defaults)
ROUTE_SCENARIO_FILES = {
    "BF-BOF": "BF_BOF_coal.yml",
    "DRI-EAF": "DRI_EAF.yml",
    "EAF-Scrap": "scrap_EAF.yml",
}

# Default post-CC picks for Finished stage (matches paper_scenarios FINAL_PICKS)
FINISHED_PICKS = {
    "Manufactured Feed (IP4)": "Stamping/calendering/lamination",
    "Finished Products": "No Coating",
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Run validation-stage scenarios for all core steel routes and "
            "emit a LaTeX table with FORGE emission factors."
        )
    )
    parser.add_argument(
        "--routes",
        default=",".join(DEFAULT_ROUTES),
        help=(
            "Comma-separated list of route presets to run "
            "(default: BF-BOF,DRI-EAF,EAF-Scrap)"
        ),
    )
    parser.add_argument(
        "--data",
        default="datasets/steel/likely",
        help="Dataset directory (default: datasets/steel/likely)",
    )
    parser.add_argument(
        "--stage",
        default="Cast",
        help="Stage key to use for all routes (default: Cast, i.e., Validation/as-cast).",
    )
    parser.add_argument(
        "--country",
        default="BRA",
        help="Grid country code for electricity EF (default: BRA)",
    )
    parser.add_argument(
        "--demand",
        type=float,
        default=1000.0,
        help="Demand quantity at stage in kg (default: 1000 kg)",
    )
    parser.add_argument(
        "--out",
        default="results/validation_routes_bra.tex",
        help="Output path for LaTeX table (default: results/validation_routes_bra.tex)",
    )
    args = parser.parse_args(argv)

    data_dir = str(Path(args.data))
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    routes = [r.strip() for r in str(args.routes).split(",") if r.strip()]

    results: list[tuple[str, float]] = []

    for route in routes:
        stage_key = args.stage

        # Load route-default scenario (if present) to mirror app defaults
        scenario: dict = {}
        scen_name = ROUTE_SCENARIO_FILES.get(route)
        if scen_name:
            scen_path = Path(data_dir) / "scenarios" / scen_name
            if scen_path.exists():
                try:
                    payload = yaml.safe_load(scen_path.read_text(encoding="utf-8")) or {}
                    if isinstance(payload, dict):
                        scenario = payload
                except Exception:
                    scenario = {}

        scn = ScenarioInputs(
            country_code=args.country,
            scenario=scenario,
            route=RouteConfig(
                route_preset=route,
                stage_key=stage_key,
                demand_qty=args.demand,
                picks_by_material=(FINISHED_PICKS if stage_key == "Finished" else {}),
            ),
        )
        out = run_scenario(data_dir, scn)
        total_kg = float(out.total_co2e_kg or 0.0)
        ef_t_per_t = total_kg / args.demand
        results.append((route, stage_key, ef_t_per_t))

    lines: list[str] = []
    lines.append("% Auto-generated by scripts/generate_validation_table.py")
    lines.append(
        f"% Data: {data_dir}, stage={args.stage}, country={args.country}, demand={args.demand} kg"
    )
    lines.append("\\begin{tabular}{l c c c}")
    lines.append("\\toprule")
    lines.append("Route & Stage & Country & FORGE EF (tCO$_2$e/t steel)\\\\")
    lines.append("\\midrule")
    for route, stage_key, ef in results:
        ef_str = f"{ef:.3f}"
        lines.append(f"{route} & {stage_key} & {args.country} & {ef_str}\\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote LaTeX table to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
