Metallurgical Aluminum: Metallurgical Aluminum from Series 1
Basic Aluminum Products: Raw Aluminum (extrusion)
Manufactured Aluminum Products: Direct use of Basic Aluminum Products
Finished Aluminum Products: No Coating
